In [6]:
from PIL import ImageTk, Image
import numpy as np
import sys
import os
import csv

In [15]:
def createFileList(myDir, format='.png'):
    fileList = []
    print(myDir)
    labels = []
    names = []
    keywords = {"F" : "1","S": "0",} # keys and values to be changed as needed
    for root, dirs, files in os.walk(myDir, topdown=True):
        for name in files:
            if name.endswith(format):
                fullName = os.path.join(root, name)
                fileList.append(fullName)
            for keyword in keywords:
                if keyword in name:
                    labels.append(keywords[keyword])
                else:
                    continue
            names.append(name)
    return fileList, labels, names
# load the original image
myFileList, labels, names  = createFileList('Content/')
i = 0
for file in myFileList:
    print(file)
    img_file = Image.open(file).convert('RGB')
    # img_file.show()
# get original image parameters...
    arr = np.array(img_file)
    # record the original shape
    shape = arr.shape
    # make a 1-dimensional view of arr
    value = arr.ravel()
    # convert it to a matrix

# Make image Greyscale
    #img_grey.save('result.png')
    #img_grey.show()
# Save Greyscale values
    i +=1
    
    print(value)
    f = open("letters.csv", 'a', newline='')
    writer = csv.writer(f)
    writer.writerow(value)

Content/
Content/First (1).png
[255 255 255 ... 255 255 255]
Content/First (10).png
[255 255 255 ... 255 255 255]
Content/First (11).png
[255 255 255 ... 255 255 255]
Content/First (12).png
[255 255 255 ... 255 255 255]
Content/First (13).png
[255 255 255 ... 255 255 255]
Content/First (14).png
[255 255 255 ... 255 255 255]
Content/First (15).png
[255 255 255 ... 255 255 255]
Content/First (16).png
[255 255 255 ... 255 255 255]
Content/First (17).png
[255 255 255 ... 255 255 255]
Content/First (18).png
[255 255 255 ... 255 255 255]
Content/First (19).png
[255 255 255 ... 255 255 255]
Content/First (2).png
[255 255 255 ... 255 255 255]
Content/First (20).png
[255 255 255 ... 255 255 255]
Content/First (21).png
[255 255 255 ... 255 255 255]
Content/First (22).png
[255 255 255 ... 255 255 255]
Content/First (23).png
[255 255 255 ... 255 255 255]
Content/First (24).png
[255 255 255 ... 255 255 255]
Content/First (25).png
[255 255 255 ... 255 255 255]
Content/First (26).png
[255 255 255 ...

In [17]:
X_train = np.loadtxt('letters.csv', delimiter = ',')

print("Shape of X_train: ", X_train.shape)

Shape of X_train:  (100, 67500)


In [24]:
f = open("labels.csv", 'a', newline='')
writer = csv.writer(f)

for x in range (40):
    writer.writerow('1')

for x in range (40):
    writer.writerow('0')

In [23]:
f = open("labels_test.csv", 'a', newline='')
writer = csv.writer(f)

for x in range (10):
    writer.writerow('1')

for x in range (10):
    writer.writerow('0')